controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#

# -----------------------------------------------------------------------------

# acceuil:
#     path: /vehicules
#     controller: App\Controller\VehiculeController::index

# vehicule_new:
#     path: /vehicules/new
#     controller: App\Controller\VehiculeController::new

# vehicule_show:
#     path:  /vehicules/{id}
#     controller: App\Controller\VehiculeController::show
#     requirements:
#     # id: '[0-9]{1,10}'
#     # id: '[0-9]{1,}'
#     # id: '\d{1,}'
#      id: '\d+'

# vehicule_modify:
#     path: /vehicules/modify/{id}
#     controller: App\Controller\VehiculeController::modify
#     requirements:
#      id: '\d+'

# vehicule_delete:
#     path: /vehicules/delete/{id}
#     controller: App\Controller\VehiculeController::delete
#     requirements:
#      id: '\d+'


    

        



